# Generated by Django 4.2 on 2024-07-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='images_book',
            field=models.ImageField(default='placeholder.png', upload_to='books/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
