# Generated by Django 4.2 on 2024-07-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_images_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='images_book',
            field=models.ImageField(null=True, upload_to='books/%Y/%m/%d'),
        ),
    ]
