# Generated by Django 4.2 on 2024-07-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_book_images_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='images_book',
            field=models.ImageField(blank=True, null=True, upload_to='books/%Y/%m/%d'),
        ),
    ]
