# Generated by Django 4.2 on 2024-07-29 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_comment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default='', max_length=700),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('book', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('book', 'user')},
        ),
    ]
