# Generated by Django 4.2 on 2024-07-29 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_book_description_alter_comment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
    ]
