# Generated by Django 4.2 on 2024-07-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_comment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(related_name='genre_books', to='core.genre'),
        ),
    ]
