# Generated by Django 4.2 on 2024-07-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_book_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['id'], name='core_genre_id_cb1dab_idx'),
        ),
    ]
